import { CampaignLevel } from '@/types/game';

export const CAMPAIGN_WORLDS = [
  {
    id: 1,
    name: 'Mundo 1: Floresta dos Bichos',
    description: 'Comece sua jornada desvendando a rica fauna brasileira. Letras em direções diretas.',
    icon: 'Trees',
    themeColor: 'from-emerald-600 to-teal-800',
    borderColor: 'border-emerald-500/40',
    requiredStars: 0,
  },
  {
    id: 2,
    name: 'Mundo 2: Sabores da Terra',
    description: 'Descubra frutas tropicais e iguarias típicas. Introdução das diagonais.',
    icon: 'Apple',
    themeColor: 'from-amber-600 to-orange-800',
    borderColor: 'border-amber-500/40',
    requiredStars: 8,
  },
  {
    id: 3,
    name: 'Mundo 3: Maravilhas do Globo',
    description: 'Viaje por capitais, montanhas e monumentos. Grades maiores e vocabulário amplo.',
    icon: 'Globe',
    themeColor: 'from-blue-600 to-indigo-800',
    borderColor: 'border-blue-500/40',
    requiredStars: 18,
  },
  {
    id: 4,
    name: 'Mundo 4: Fronteira Tecnológica',
    description: 'Inteligência, códigos e algoritmos. Atenção: palavras podem estar de trás para frente!',
    icon: 'Cpu',
    themeColor: 'from-cyan-600 to-blue-800',
    borderColor: 'border-cyan-500/40',
    requiredStars: 30,
  },
  {
    id: 5,
    name: 'Mundo 5: Cosmos & Infinito',
    description: 'O teste supremo de percepção. Galáxias distantes em todas as 8 direções.',
    icon: 'Sparkles',
    themeColor: 'from-purple-600 to-fuchsia-800',
    borderColor: 'border-purple-500/40',
    requiredStars: 44,
  },
];

export const CAMPAIGN_LEVELS: CampaignLevel[] = [
  // MUNDO 1: Floresta dos Bichos (Fácil)
  {
    id: 1,
    worldId: 1,
    worldName: 'Mundo 1: Floresta dos Bichos',
    levelNumber: 1,
    title: 'Primeiros Passos na Mata',
    categoryId: 'animais-brasileiros',
    difficulty: 'facil',
    gridSize: 9,
    wordCount: 5,
    timeTargetSeconds: 90,
    description: 'Encontre 5 animais brasileiros na horizontal e vertical.',
  },
  {
    id: 2,
    worldId: 1,
    worldName: 'Mundo 1: Floresta dos Bichos',
    levelNumber: 2,
    title: 'Caminho das Águas',
    categoryId: 'animais-brasileiros',
    difficulty: 'facil',
    gridSize: 9,
    wordCount: 6,
    timeTargetSeconds: 100,
    description: 'Procure os animais das margens dos grandes rios.',
  },
  {
    id: 3,
    worldId: 1,
    worldName: 'Mundo 1: Floresta dos Bichos',
    levelNumber: 3,
    title: 'Copa das Árvores',
    categoryId: 'animais-brasileiros',
    difficulty: 'facil',
    gridSize: 10,
    wordCount: 7,
    timeTargetSeconds: 120,
    description: 'Aves e macacos escondidos entre os galhos.',
  },
  {
    id: 4,
    worldId: 1,
    worldName: 'Mundo 1: Floresta dos Bichos',
    levelNumber: 4,
    title: 'Coração da Selva',
    categoryId: 'animais-brasileiros',
    difficulty: 'facil',
    gridSize: 10,
    wordCount: 8,
    timeTargetSeconds: 140,
    description: 'Complete o primeiro mundo encontrando 8 espécies da fauna!',
  },

  // MUNDO 2: Sabores da Terra (Médio)
  {
    id: 5,
    worldId: 2,
    worldName: 'Mundo 2: Sabores da Terra',
    levelNumber: 1,
    title: 'Pomar Tropical',
    categoryId: 'frutas-culinaria',
    difficulty: 'medio',
    gridSize: 11,
    wordCount: 6,
    timeTargetSeconds: 120,
    description: 'Frutas brasileiras. Cuidado: as palavras agora podem estar em diagonal!',
  },
  {
    id: 6,
    worldId: 2,
    worldName: 'Mundo 2: Sabores da Terra',
    levelNumber: 2,
    title: 'Quitutes Tradicionais',
    categoryId: 'frutas-culinaria',
    difficulty: 'medio',
    gridSize: 11,
    wordCount: 7,
    timeTargetSeconds: 135,
    description: 'Tapioca, brigadeiro e feijoada espalhados pela grade.',
  },
  {
    id: 7,
    worldId: 2,
    worldName: 'Mundo 2: Sabores da Terra',
    levelNumber: 3,
    title: 'Banquete dos Biomas',
    categoryId: 'frutas-culinaria',
    difficulty: 'medio',
    gridSize: 12,
    wordCount: 8,
    timeTargetSeconds: 150,
    description: 'Do Cerrado à Amazônia, encontre 8 sabores marcantes.',
  },
  {
    id: 8,
    worldId: 2,
    worldName: 'Mundo 2: Sabores da Terra',
    levelNumber: 4,
    title: 'Festa da Culinária',
    categoryId: 'frutas-culinaria',
    difficulty: 'medio',
    gridSize: 12,
    wordCount: 9,
    timeTargetSeconds: 180,
    description: 'Desafio completo da culinária com 9 palavras saborosas.',
  },

  // MUNDO 3: Maravilhas do Globo (Médio-Avançado)
  {
    id: 9,
    worldId: 3,
    worldName: 'Mundo 3: Maravilhas do Globo',
    levelNumber: 1,
    title: 'Cartões-Postais',
    categoryId: 'geografia-cidades',
    difficulty: 'medio',
    gridSize: 12,
    wordCount: 7,
    timeTargetSeconds: 140,
    description: 'Monumentos e cidades célebres do mundo inteiro.',
  },
  {
    id: 10,
    worldId: 3,
    worldName: 'Mundo 3: Maravilhas do Globo',
    levelNumber: 2,
    title: 'Extremos da Terra',
    categoryId: 'geografia-cidades',
    difficulty: 'medio',
    gridSize: 13,
    wordCount: 8,
    timeTargetSeconds: 160,
    description: 'Geleiras, desertos ardentes e florestas colossais.',
  },
  {
    id: 11,
    worldId: 3,
    worldName: 'Mundo 3: Maravilhas do Globo',
    levelNumber: 3,
    title: 'Rotas Antigas',
    categoryId: 'mitologia-historia',
    difficulty: 'medio',
    gridSize: 13,
    wordCount: 8,
    timeTargetSeconds: 170,
    description: 'Civilizações milenares e seus heróis mitológicos.',
  },
  {
    id: 12,
    worldId: 3,
    worldName: 'Mundo 3: Maravilhas do Globo',
    levelNumber: 4,
    title: 'Maravilhas Eternas',
    categoryId: 'geografia-cidades',
    difficulty: 'medio',
    gridSize: 13,
    wordCount: 10,
    timeTargetSeconds: 190,
    description: 'Encontre 10 lugares memoráveis com alta agilidade visual.',
  },

  // MUNDO 4: Fronteira Tecnológica (Difícil - Palavras Invertidas)
  {
    id: 13,
    worldId: 4,
    worldName: 'Mundo 4: Fronteira Tecnológica',
    levelNumber: 1,
    title: 'Linhas de Código',
    categoryId: 'tecnologia-futuro',
    difficulty: 'dificil',
    gridSize: 14,
    wordCount: 8,
    timeTargetSeconds: 160,
    description: 'Atenção redobrada: palavras invertidas (de trás para frente)!',
  },
  {
    id: 14,
    worldId: 4,
    worldName: 'Mundo 4: Fronteira Tecnológica',
    levelNumber: 2,
    title: 'Cérebro Artificial',
    categoryId: 'tecnologia-futuro',
    difficulty: 'dificil',
    gridSize: 14,
    wordCount: 9,
    timeTargetSeconds: 180,
    description: 'Redes neurais e automação em direções ortogonais e diagonais reversas.',
  },
  {
    id: 15,
    worldId: 4,
    worldName: 'Mundo 4: Fronteira Tecnológica',
    levelNumber: 3,
    title: 'Salto Quântico',
    categoryId: 'tecnologia-futuro',
    difficulty: 'dificil',
    gridSize: 14,
    wordCount: 10,
    timeTargetSeconds: 200,
    description: '10 termos avançados camuflados em uma grade densa.',
  },
  {
    id: 16,
    worldId: 4,
    worldName: 'Mundo 4: Fronteira Tecnológica',
    levelNumber: 4,
    title: 'Mente Conectada',
    categoryId: 'tecnologia-futuro',
    difficulty: 'dificil',
    gridSize: 14,
    wordCount: 11,
    timeTargetSeconds: 220,
    description: 'Supere o labirinto digital para abrir os portões do Cosmos.',
  },

  // MUNDO 5: Cosmos & Infinito (Mestre)
  {
    id: 17,
    worldId: 5,
    worldName: 'Mundo 5: Cosmos & Infinito',
    levelNumber: 1,
    title: 'Berçário Estelar',
    categoryId: 'astronomia-espaco',
    difficulty: 'mestre',
    gridSize: 15,
    wordCount: 9,
    timeTargetSeconds: 180,
    description: 'Nebulosas e supernovas em todas as 8 direções possíveis.',
  },
  {
    id: 18,
    worldId: 5,
    worldName: 'Mundo 5: Cosmos & Infinito',
    levelNumber: 2,
    title: 'Buraco Negro',
    categoryId: 'astronomia-espaco',
    difficulty: 'mestre',
    gridSize: 15,
    wordCount: 10,
    timeTargetSeconds: 210,
    description: 'Concentre o olhar: as palavras se cruzam intensamente.',
  },
  {
    id: 19,
    worldId: 5,
    worldName: 'Mundo 5: Cosmos & Infinito',
    levelNumber: 3,
    title: 'Horizonte de Eventos',
    categoryId: 'astronomia-espaco',
    difficulty: 'mestre',
    gridSize: 16,
    wordCount: 11,
    timeTargetSeconds: 240,
    description: 'Grade colossal 16x16 com 11 palavras cósmicas.',
  },
  {
    id: 20,
    worldId: 5,
    worldName: 'Mundo 5: Cosmos & Infinito',
    levelNumber: 4,
    title: 'Mestre do Cosmos',
    categoryId: 'astronomia-espaco',
    difficulty: 'mestre',
    gridSize: 16,
    wordCount: 12,
    timeTargetSeconds: 260,
    description: 'O grande teste final! 12 palavras em 8 direções na grade mestra.',
  },
];
