import { Category } from '@/types/game';

export const CATEGORIES: Category[] = [
  {
    id: 'animais-brasileiros',
    name: 'Fauna Brasileira & Selvagens',
    description: 'Animais emblemáticos do Pantanal, Amazônia, Cerrado e Mata Atlântica.',
    iconName: 'Trees',
    color: 'emerald',
    bgGradient: 'from-emerald-950 via-teal-950 to-slate-950',
    words: [
      { word: 'CAPIVARA', displayWord: 'Capivara', clue: 'Maior roedor do planeta', trivia: 'As capivaras são animais semi-aquáticos e extremamente sociáveis.' },
      { word: 'ONCA', displayWord: 'Onça-Pintada', clue: 'Maior felino das Américas', trivia: 'Possui a mordida mais forte entre todos os felinos em relação ao peso.' },
      { word: 'MICO', displayWord: 'Mico-Leão-Dourado', clue: 'Primata símbolo da Mata Atlântica', trivia: 'Tem uma juba dourada impressionante e vive em grupos familiares.' },
      { word: 'ARARA', displayWord: 'Arara-Azul', clue: 'Ave de plumagem azul vibrante', trivia: 'Pode viver até 50 anos e escolhe um único par para a vida inteira.' },
      { word: 'TAMANDUA', displayWord: 'Tamanduá-Bandeira', clue: 'Come milhares de formigas por dia', trivia: 'Sua língua pode atingir até 60 centímetros de comprimento.' },
      { word: 'BOTO', displayWord: 'Boto-Cor-de-Rosa', clue: 'Golfinho fluvial das águas amazônicas', trivia: 'É cercado de lendas folclóricas e consegue virar o pescoço em 180°.' },
      { word: 'LOBO', displayWord: 'Lobo-Guará', clue: 'Maior canídeo da América do Sul', trivia: 'Apesar do nome, não forma alcateias e adora comer lobeira, fruto do Cerrado.' },
      { word: 'SUCURI', displayWord: 'Sucuri', clue: 'Uma das maiores serpentes do planeta', trivia: 'Pode passar semanas digerindo uma única presa em repouso aquático.' },
      { word: 'TATU', displayWord: 'Tatu-Bola', clue: 'Consegue se fechar em uma esfera blindada', trivia: 'Foi o mascote oficial da Copa do Mundo de 2014 no Brasil.' },
      { word: 'HARPIA', displayWord: 'Harpia', clue: 'Poderosa ave de rapina da floresta', trivia: 'Também conhecida como gavião-real, possui garras maiores que as de um urso.' },
      { word: 'TUCANO', displayWord: 'Tucano-Toco', clue: 'Famoso pelo bico longo e alaranjado', trivia: 'Seu bico gigante ajuda a regular a temperatura corporal.' },
      { word: 'JAGUATIRICA', displayWord: 'Jaguatirica', clue: 'Felino de porte médio com pelagem malhada', trivia: 'Excelente nadadora e caçadora noturna muito silenciosa.' },
      { word: 'JABUTI', displayWord: 'Jabuti', clue: 'Réptil terrestre de carapaça resistente', trivia: 'Alguns indivíduos podem viver mais de 80 a 100 anos.' },
      { word: 'PREGUICA', displayWord: 'Bicho-Preguiça', clue: 'Mamífero mestre em economia de energia', trivia: 'Desce ao chão da floresta apenas uma vez por semana.' },
      { word: 'PIRARUCU', displayWord: 'Pirarucu', clue: 'Gigante peixe das bacias amazônicas', trivia: 'Precisa subir à superfície para respirar oxigênio atmosférico.' },
    ],
  },
  {
    id: 'frutas-culinaria',
    name: 'Sabores & Frutas Brasileiras',
    description: 'Delícias tropicais, pratos tradicionais e frutos da nossa terra.',
    iconName: 'Apple',
    color: 'amber',
    bgGradient: 'from-amber-950 via-orange-950 to-slate-950',
    words: [
      { word: 'ACAI', displayWord: 'Açaí', clue: 'Fruto roxo superenergético do Norte', trivia: 'Tradicionalmente consumido no Pará com farinha e peixe frito.' },
      { word: 'JABUTICABA', displayWord: 'Jabuticaba', clue: 'Frutinha doce que nasce no tronco', trivia: 'Seu nome em tupi significa "fruta em botão".' },
      { word: 'CUPUACU', displayWord: 'Cupuaçu', clue: 'Fruta parente próxima do cacau', trivia: 'Sua polpa azedinha é usada para fazer sorvetes, sucos e o "cupulate".' },
      { word: 'PITANGA', displayWord: 'Pitanga', clue: 'Pequena fruta vermelha em formato gomado', trivia: 'Riquíssima em antioxidantes e vitamina A.' },
      { word: 'GRAVIOLA', displayWord: 'Graviola', clue: 'Fruta com casca espinhosa e polpa branca cremosa', trivia: 'Conhecida pelo aroma intenso e propriedades medicinais.' },
      { word: 'MARACUJA', displayWord: 'Maracujá', clue: 'Famoso por suas propriedades calmantes', trivia: 'Sua flor exuberante é também chamada de "flor-da-paixão".' },
      { word: 'GUARANA', displayWord: 'Guaraná', clue: 'Semente estimulante da Amazônia', trivia: 'A semente madura aberta lembra visualmente a íris de um olho.' },
      { word: 'FEIJOADA', displayWord: 'Feijoada', clue: 'Prato clássico com feijão preto e carnes', trivia: 'Um dos patrimônios gastronômicos mais celebrados do país.' },
      { word: 'TAPIOCA', displayWord: 'Tapioca', clue: 'Massa feita com fécula de mandioca', trivia: 'Alimento básico ancestral dos povos indígenas tupis-guaranis.' },
      { word: 'MOQUECA', displayWord: 'Moqueca', clue: 'Cozido perfumado de peixe com temperos', trivia: 'Famosa nas versões capixaba (com urucum) e baiana (com azeite de dendê).' },
      { word: 'BRIGADEIRO', displayWord: 'Brigadeiro', clue: 'Doce de leite condensado e chocolate', trivia: 'Criado no Rio de Janeiro na década de 1940 durante uma campanha eleitoral.' },
      { word: 'PAMONHA', displayWord: 'Pamonha', clue: 'Massa de milho verde cozida na palha', trivia: 'Iguaria típica das festas juninas em todo o Brasil.' },
      { word: 'CAJU', displayWord: 'Caju', clue: 'Possui castanha no topo e pedúnculo suculento', trivia: 'A verdadeira fruta botânica é a castanha; a parte suculenta é um pseudofruto!' },
      { word: 'PEQUI', displayWord: 'Pequi', clue: 'Fruto marcante do Cerrado com espinhos internos', trivia: 'Exige cuidado ao comer para não morder os minúsculos espinhos do caroço.' },
    ],
  },
  {
    id: 'tecnologia-futuro',
    name: 'Tecnologia & Inovação',
    description: 'Conceitos do mundo digital, inteligência artificial e computação moderna.',
    iconName: 'Cpu',
    color: 'cyan',
    bgGradient: 'from-cyan-950 via-blue-950 to-slate-950',
    words: [
      { word: 'ALGORITMO', displayWord: 'Algoritmo', clue: 'Sequência lógica de instruções para resolver problemas', trivia: 'O termo vem do matemático persa do século IX, Al-Khwarizmi.' },
      { word: 'ROBOTICA', displayWord: 'Robótica', clue: 'Ciência que desenvolve máquinas autônomas', trivia: 'A palavra robô vem do tcheco "robota", que significa trabalho forçado.' },
      { word: 'QUANTICO', displayWord: 'Quântico', clue: 'Computação baseada nos princípios da física subatômica', trivia: 'Usa qubits que podem existir em múltiplos estados simultâneos (superposição).' },
      { word: 'HOLOGRAMA', displayWord: 'Holograma', clue: 'Projeção tridimensional gerada por luz', trivia: 'A holografia foi inventada pelo físico húngaro Dennis Gabor em 1947.' },
      { word: 'SATELITE', displayWord: 'Satélite', clue: 'Corpo artificial em órbita transmitindo dados', trivia: 'O Sputnik 1 foi o primeiro satélite artificial colocado em órbita, em 1957.' },
      { word: 'CIBERNETICA', displayWord: 'Cibernética', clue: 'Estudo do controle e comunicação em máquinas e seres vivos', trivia: 'Conceito formalizado por Norbert Wiener no final dos anos 1940.' },
      { word: 'INTERNET', displayWord: 'Internet', clue: 'Rede mundial de computadores interconectados', trivia: 'A primeira mensagem enviada pela ARPANET em 1969 foi a tentativa de digitar "LOGIN".' },
      { word: 'MICROCHIP', displayWord: 'Microchip', clue: 'Circuito integrado com bilhões de transistores', trivia: 'Hoje contêm estruturas com tamanho de poucos nanômetros, menores que vírus.' },
      { word: 'AUTOMACAO', displayWord: 'Automação', clue: 'Processos produtivos operados sem intervenção direta', trivia: 'Aumenta precisão e segurança em indústrias e sistemas críticos.' },
      { word: 'CRIPTOGRAFIA', displayWord: 'Criptografia', clue: 'Técnica de segurança para proteger informações', trivia: 'Júlio César usava uma cifra simples de transposição para trocar mensagens secretas.' },
      { word: 'NEURAL', displayWord: 'Rede Neural', clue: 'Modelo computacional inspirado no cérebro biológico', trivia: 'Capaz de aprender padrões complexos através do ajuste de pesos sinápticos.' },
      { word: 'NANOTECNOLOGIA', displayWord: 'Nanotecnologia', clue: 'Manipulação de matéria em escala molecular', trivia: 'Um nanômetro é um bilionésimo de metro, cerca de 100 mil vezes menor que um fio de cabelo.' },
      { word: 'BIOMETRIA', displayWord: 'Biometria', clue: 'Identificação por características físicas únicas', trivia: 'Inclui reconhecimento facial, íris, impressão digital e até padrão vascular.' },
    ],
  },
  {
    id: 'astronomia-espaco',
    name: 'Astronomia & Cosmos',
    description: 'Estrelas, galáxias misteriosas, planetas e fenômenos espaciais.',
    iconName: 'Sparkles',
    color: 'purple',
    bgGradient: 'from-purple-950 via-indigo-950 to-slate-950',
    words: [
      { word: 'SUPERNOVA', displayWord: 'Supernova', clue: 'Explosão cósmica espetacular de uma estrela moribunda', trivia: 'Pode brilhar mais do que uma galáxia inteira durante algumas semanas.' },
      { word: 'ANDROMEDA', displayWord: 'Andrômeda', clue: 'A grande galáxia espiral mais próxima da Via Láctea', trivia: 'Está a cerca de 2,5 milhões de anos-luz da Terra e colidirá conosco daqui a 4 bilhões de anos.' },
      { word: 'NEBULOSA', displayWord: 'Nebulosa', clue: 'Nuvem colossal de gás e poeira onde nascem estrelas', trivia: 'Algumas nebulosas famosas são os "Pilares da Criação" na Nebulosa da Águia.' },
      { word: 'ASTEROIDE', displayWord: 'Asteroide', clue: 'Corpo rochoso que orbita o Sol', trivia: 'A maioria está concentrada no cinturão entre Marte e Júpiter.' },
      { word: 'GRAVIDADE', displayWord: 'Gravidade', clue: 'Força fundamental de atração entre corpos com massa', trivia: 'Einstein descreveu a gravidade como a curvatura do próprio tecido espaço-tempo.' },
      { word: 'TELESCOPIO', displayWord: 'Telescópio', clue: 'Instrumento óptico para perscrutar o cosmos', trivia: 'O telescópio James Webb opera a 1,5 milhão de km da Terra em temperaturas quase no zero absoluto.' },
      { word: 'EXOPLANETA', displayWord: 'Exoplaneta', clue: 'Planeta situado fora do nosso Sistema Solar', trivia: 'Mais de 5.500 exoplanetas já foram catalogados pela humanidade.' },
      { word: 'COMETA', displayWord: 'Cometa', clue: 'Bola de gelo e rocha com cauda brilhante', trivia: 'O cometa Halley visita o interior do Sistema Solar a cada 76 anos.' },
      { word: 'PULSAR', displayWord: 'Pulsar', clue: 'Estrela de nêutrons magnética de rotação ultrarrápida', trivia: 'Emite feixes de radiação com precisão comparável a relógios atômicos.' },
      { word: 'ECLIPSE', displayWord: 'Eclipse', clue: 'Ocultação temporária de um astro por outro', trivia: 'A coincidência perfeita do tamanho aparente do Sol e da Lua permite eclipses solares totais na Terra.' },
      { word: 'CONSTELACAO', displayWord: 'Constelação', clue: 'Grupo de estrelas com padrão reconhecível no céu', trivia: 'A União Astronômica Internacional reconhece oficialmente 88 constelações modernas.' },
      { word: 'AURORA', displayWord: 'Aurora Polar', clue: 'Luzes mágicas provocadas por ventos solares na atmosfera', trivia: 'Chamada de Aurora Boreal no hemisfério norte e Austral no hemisfério sul.' },
    ],
  },
  {
    id: 'geografia-cidades',
    name: 'Cidades & Maravilhas do Mundo',
    description: 'Metrópoles fascinantes, paisagens geográficas e monumentos.',
    iconName: 'Globe',
    color: 'blue',
    bgGradient: 'from-blue-950 via-slate-900 to-slate-950',
    words: [
      { word: 'AMAZONIA', displayWord: 'Amazônia', clue: 'Maior floresta tropical e bacia hidrográfica do globo', trivia: 'Abriga mais de 10% de todas as espécies vivas conhecidas do planeta.' },
      { word: 'PATAGONIA', displayWord: 'Patagônia', clue: 'Região selvagem de geleiras no extremo sul americano', trivia: 'Famosa pelos picos pontiagudos de Torres del Paine e glaciares gigantescos.' },
      { word: 'CATARATAS', displayWord: 'Cataratas do Iguaçu', clue: 'Impressionante conjunto de 275 quedas d\'água', trivia: 'A "Garganta do Diabo" tem mais de 80 metros de altura e fluxo avassalador.' },
      { word: 'SAARA', displayWord: 'Deserto do Saara', clue: 'Maior deserto quente do mundo', trivia: 'Sua extensão territorial é quase do tamanho do Brasil inteiro.' },
      { word: 'HIMALAIA', displayWord: 'Himalaia', clue: 'Cordilheira asiática onde fica o Monte Everest', trivia: 'Continua crescendo alguns milímetros a cada ano pela colisão das placas tectônicas.' },
      { word: 'NORONHA', displayWord: 'Fernando de Noronha', clue: 'Arquipélago vulcânico paradisíaco brasileiro', trivia: 'Patrimônio Mundial da UNESCO famoso pela baía com golfinhos rotadores.' },
      { word: 'PIRAMIDES', displayWord: 'Pirâmides de Gizé', clue: 'Monumentos milenares do Egito Antigo', trivia: 'A Grande Pirâmide de Quéops foi a construção mais alta do mundo por mais de 3.800 anos.' },
      { word: 'COLISEU', displayWord: 'Coliseu', clue: 'Anfiteatro icônico na Roma Antiga', trivia: 'Tinha capacidade para mais de 50 mil espectadores e contava com teto de lona retrátil.' },
      { word: 'TOKIO', displayWord: 'Tóquio', clue: 'Mais populosa área metropolitana do mundo', trivia: 'Combina arranha-céus ultramodernos com santuários xintoístas centenários.' },
      { word: 'VENEZA', displayWord: 'Veneza', clue: 'Histórica cidade italiana construída sobre canais', trivia: 'É composta por 118 pequenas ilhas ligadas por mais de 400 pontes.' },
      { word: 'MACHU', displayWord: 'Machu Picchu', clue: 'Cidadela inca sagrada nos Andes peruanos', trivia: 'Construída com blocos de pedra polida encaixados sem o uso de argamassa.' },
      { word: 'SERENGETI', displayWord: 'Serengeti', clue: 'Parque nacional africano com a Grande Migração', trivia: 'Milhões de gnus e zebras atravessam planícies enfrentando rios repletos de crocodilos.' },
    ],
  },
  {
    id: 'mitologia-historia',
    name: 'História & Mitologias',
    description: 'Deuses ancestrais, lendas fascinantes e civilizações antigas.',
    iconName: 'Flame',
    color: 'orange',
    bgGradient: 'from-orange-950 via-rose-950 to-slate-950',
    words: [
      { word: 'TUPA', displayWord: 'Tupã', clue: 'Divindade indígena do trovão e da criação', trivia: 'Na cosmogonia tupi-guarani, representa a voz soberana da natureza cósmica.' },
      { word: 'ANUBIS', displayWord: 'Anúbis', clue: 'Deus egípcio com cabeça de chacal', trivia: 'Guiava as almas ao julgamento onde o coração era pesado contra a pena da verdade.' },
      { word: 'VALQUIRIA', displayWord: 'Valquíria', clue: 'Donzela guerreira da mitologia nórdica', trivia: 'Conduzia guerreiros honrados tombados em combate aos salões de Valhala.' },
      { word: 'FARAO', displayWord: 'Faraó', clue: 'Líder supremo e intermediário divino no Egito', trivia: 'Governavam tanto a ordem política quanto os ritos sacerdotais sagrados.' },
      { word: 'GLADIADOR', displayWord: 'Gladiador', clue: 'Combatente armado em arenas do Império Romano', trivia: 'Alguns gladiadores se tornavam verdadeiras celebridades na Roma Antiga.' },
      { word: 'SAMURAI', displayWord: 'Samurai', clue: 'Nobre guerreiro do Japão feudal regido pelo Bushido', trivia: 'O código Bushido exigia lealdade absoluta, honra marcial e autocontrole.' },
      { word: 'ESPARTA', displayWord: 'Esparta', clue: 'Cidade-estado grega célebre pela disciplina militar', trivia: 'Os jovens espartanos iniciavam treinamento rigoroso de sobrevivência aos sete anos.' },
      { word: 'ASTECA', displayWord: 'Civilização Asteca', clue: 'Povo que ergueu a esplêndida Tenochtitlán', trivia: 'Construíram jardins flutuantes chamados chinampas para agricultura sustentável.' },
      { word: 'CENTAURO', displayWord: 'Centauro', clue: 'Criatura mítica metade humano, metade cavalo', trivia: 'Na mitologia grega, Quíron era o mais sábio dos centauros e mestre de heróis.' },
      { word: 'FENIX', displayWord: 'Fênix', clue: 'Pássaro lendário que renasce das próprias cinzas', trivia: 'Simboliza renovação perpétua, imortalidade e resiliência na história.' },
      { word: 'MINOTAURO', displayWord: 'Minotauro', clue: 'Monstro com cabeça de touro encarcerado no labirinto de Creta', trivia: 'Dédalo construiu o labirinto tão complexo que ele próprio quase não escapou.' },
      { word: 'CLEOPATRA', displayWord: 'Cleópatra', clue: 'Última governante ativa do Reino Ptolemaico do Egito', trivia: 'Falava múltiplos idiomas e era amplamente elogiada pelo carisma e inteligência.' },
    ],
  },
  {
    id: 'esportes-aventura',
    name: 'Esportes & Aventura',
    description: 'Adrenalina, modalidades olímpicas e espírito esportivo.',
    iconName: 'Trophy',
    color: 'rose',
    bgGradient: 'from-rose-950 via-red-950 to-slate-950',
    words: [
      { word: 'CAPOEIRA', displayWord: 'Capoeira', clue: 'Arte marcial e dança afro-brasileira ao som do berimbau', trivia: 'Reconhecida como Patrimônio Cultural Imaterial da Humanidade pela UNESCO.' },
      { word: 'SURFE', displayWord: 'Surfe', clue: 'Deslizar sobre as ondas com uma prancha', trivia: 'O Brasil conta com a famosa "Brazilian Storm" dominando títulos mundiais.' },
      { word: 'MARATONA', displayWord: 'Maratona', clue: 'Clássica corrida de rua de 42,195 quilômetros', trivia: 'A distância foi oficializada nas Olimpíadas de Londres em 1908 para passar pelo Castelo de Windsor.' },
      { word: 'ESCALADA', displayWord: 'Escalada', clue: 'Ascensão técnica em rochas ou paredões artificiais', trivia: 'Estreou como esporte olímpico oficial nos Jogos de Tóquio 2020.' },
      { word: 'CANOAGEM', displayWord: 'Canoagem', clue: 'Velocidade e manobras em rios e lagos com remo', trivia: 'O canoísta brasileiro Isaquias Queiroz é um dos maiores medalhistas do esporte.' },
      { word: 'CICLISMO', displayWord: 'Ciclismo', clue: 'Competições sobre duas rodas no asfalto ou trilhas', trivia: 'O Tour de France é disputado desde 1903 cobrindo mais de 3.000 quilômetros.' },
      { word: 'VOLEIBOL', displayWord: 'Voleibol', clue: 'Jogo de equipe dinâmico com toques, manchetes e bloqueios', trivia: 'Foi criado em 1895 nos EUA com o nome original de Mintonette.' },
      { word: 'BASQUETE', displayWord: 'Basquetebol', clue: 'Arremessar a bola na cesta de 3,05 metros de altura', trivia: 'No primeiro jogo, cestos de colher pêssegos foram usados como aros!' },
      { word: 'ATLETISMO', displayWord: 'Atletismo', clue: 'Conjunto ancestral de corridas, saltos e lançamentos', trivia: 'Considerado a forma mais antiga de competição desportiva organizada.' },
      { word: 'SKATE', displayWord: 'Skateboarding', clue: 'Manobras sobre prancha de quatro rodinhas', trivia: 'Surgiu na Califórnia nos anos 1950 quando surfistas queriam treinar no asfalto.' },
      { word: 'GINASTICA', displayWord: 'Ginástica Artística', clue: 'Equilíbrio, força e acrobacias em aparelhos', trivia: 'O Brasil é referência mundial com nomes como Rebeca Andrade e Daiane dos Santos.' },
      { word: 'FUTEBOL', displayWord: 'Futebol', clue: 'Paixão nacional disputada entre duas equipes de 11 jogadores', trivia: 'O Brasil é o único país a ter disputado todas as edições da Copa do Mundo.' },
    ],
  },
  {
    id: 'natureza-elementos',
    name: 'Elementos da Terra',
    description: 'Rios cristalinos, montanhas, florestas e forças geológicas.',
    iconName: 'Compass',
    color: 'teal',
    bgGradient: 'from-teal-950 via-emerald-950 to-slate-950',
    words: [
      { word: 'CACHOEIRA', displayWord: 'Cachoeira', clue: 'Queda livre torrencial de água límpida', trivia: 'As Cataratas do Salto Ángel na Venezuela são a cachoeira mais alta do mundo (979 metros).' },
      { word: 'VULCAO', displayWord: 'Vulcão', clue: 'Abertura na crosta que expele magma e cinzas', trivia: 'Existem cerca de 1.500 vulcões potencialmente ativos no planeta Terra.' },
      { word: 'GELEIRA', displayWord: 'Geleira', clue: 'Massa espessa de gelo em movimento lento', trivia: 'As geleiras armazenam cerca de 69% de toda a água doce do planeta.' },
      { word: 'RECIFE', displayWord: 'Recife de Coral', clue: 'Estrutura biológica marinha de riquíssima biodiversidade', trivia: 'A Grande Barreira de Coral na Austrália é visível do espaço sideral.' },
      { word: 'CANION', displayWord: 'Cânion', clue: 'Profundo vale rochoso esculpido por erosão fluvial', trivia: 'O Grand Canyon nos Estados Unidos atinge até 1.800 metros de profundidade.' },
      { word: 'FLORESTA', displayWord: 'Floresta', clue: 'Ecossistema dominado por árvores altas e fauna rica', trivia: 'Florestas cobrem cerca de 31% da superfície terrestre global.' },
      { word: 'ARQUIPELAGO', displayWord: 'Arquipélago', clue: 'Grupo ou cadeia de ilhas oceânicas', trivia: 'A Indonésia é o maior país arquipélago do mundo, com mais de 17 mil ilhas.' },
      { word: 'MANGUEZAL', displayWord: 'Manguezal', clue: 'Berçário da vida marinha em zonas litorâneas', trivia: 'Suas raízes aéreas protegem a costa contra a erosão causada por marés e tempestades.' },
      { word: 'GEYSER', displayWord: 'Gêiser', clue: 'Fonte termal que expele jatos periódicos de água quente', trivia: 'O nome deriva de Geysir, na Islândia, do verbo germânico "jorrar".' },
      { word: 'SAVANA', displayWord: 'Savana', clue: 'Bioma de vegetação aberta com árvores esparsas', trivia: 'No Brasil, o Cerrado é considerado a savana de maior biodiversidade do mundo.' },
      { word: 'ESTALACTITE', displayWord: 'Estalactite', clue: 'Formação mineral que desce do teto de cavernas', trivia: 'Leva séculos para crescer meros centímetros com o gotejar da água calcária.' },
      { word: 'RESTINGA', displayWord: 'Restinga', clue: 'Vegetação costeira adaptada ao solo arenoso e salino', trivia: 'Essencial para a fixação de dunas e proteção da faixa de praia.' },
    ],
  },
];

export function getCategoryById(id: string): Category {
  return CATEGORIES.find(c => c.id === id) || CATEGORIES[0];
}
